AWSTemplateFormatVersion: '2010-09-09'
Description: 'Discord Bot EC2Instance'
Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: EC2DiscordKey

Resources:

  DiscordBotServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: 't2.micro'
      SecurityGroups:
      - Ref: DiscordBotServerSecurityGroup
      KeyName:
        Ref: KeyName
      ImageId: 'ami-0fad7378adf284ce0'

  DiscordBotServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: '0.0.0.0/0'

Outputs:
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - DiscordBotServer
      - PublicIp
