AWSTemplateFormatVersion: '2010-09-09'
Description: 'Discord Bot EC2Instance'
Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: EC2DiscordKey

Resources:

  DiscordBotServerAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref 'DiscordBotServerLaunchConfig'
      MinSize: '1'
      MaxSize: '1'
      AvailabilityZones:
        Fn::GetAZs: "eu-west-1"

  DiscordBotServerLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      KeyName: !Ref 'KeyName'
      ImageId: 'ami-01e584c365688abdc'
      SecurityGroups: [!Ref 'DiscordBotServerSecurityGroup']
      InstanceType: 't2.micro'

  DiscordBotServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: '192.168.0.0/30'
